services:
  prod:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app # Bind mount the current directory for live code updates
      - /home/node/app/node_modules # Prevent overwriting node_modules with an empty host folder
  dev:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app # Bind mount the current directory for live code updates
      - /home/node/app/node_modules # Prevent overwriting node_modules with an empty host folder
